In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:

# datasets

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [2]:
# refining the data replacing 'NaN' or blank spaces in the data to the mean of the values in the respective columns.
# giving string a dumb variable or a number to make it easy for our model to work with it


# Load the dataset
datasets = pd.read_csv('Data.csv')
x = datasets.iloc[:, 0:-1].values  # Features
y = datasets.iloc[:, -1].values   # Target variable
# print(x)

# taking care of missing data

# If you have missing values, you can uncomment and use SimpleImputer
# from sklearn.impute import SimpleImputer
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
x[:, 1:3] = imputer.fit_transform(x[:, 1:3])


# encoding the dummy variables (strings) in to integer


# Label encode the first categorical column (assuming it's the first column)
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelEncoder_X = LabelEncoder()
x[:, 0] = labelEncoder_X.fit_transform(x[:, 0])  # Encode the string as numbers

#hot encoding (making different columns for each dummy variable and fill with 0 and 1 to remove the precedence or order error in our model)


# One-hot encode the first categorical column (assuming it's the first column)
onehotencoder = OneHotEncoder(sparse_output=False)  # Use sparse=False to get a dense array
x_encoded = onehotencoder.fit_transform(x[:, 0].reshape(-1, 1)) # -1 calculates the row in the datasets and 1 is the first column
# print(x_encoded) its those three columns of different values
# Combine the one-hot encoded values with the original numerical columns
x = x[:, 1:]  # Exclude the original categorical column
x = np.column_stack((x_encoded, x))
# Now x contains the one-hot encoded values along with the original numerical columns
labelEncoder_Y = LabelEncoder()
y = labelEncoder_Y.fit_transform(y)
encoded_dataset = np.column_stack((x,y))
# print('original dataset')
# print(encoded_dataset)


#train testing our dataset


from sklearn.model_selection import train_test_split
# print(x)
# print(y)
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

# print('y-train')
# print(y_train)

# print('y_test')
# print(y_test)



# feature scaling

from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
print('x-train')
print(X_train)
X_test = sc_X.transform(X_test)
print('x-test')
print(X_test)

x-train
[[-1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [ 1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [-1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [-1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [ 1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [-1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [ 1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [ 1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]]
x-test
[[-1.          2.64575131 -0.77459667 -1.45882927 -0.90166297]
 [-1.          2.64575131 -0.77459667  1.98496442  2.13981082]]