In [1]:
import pandas as pd

   OrderDate   Region       Rep     Item  Units  Unit Cost       Total
0     1/6/21     East     Jones   Pencil     95       1.99     189.05
1    1/23/21  Central    Kivell   Binder     50      19.99     999.50
2     2/9/21  Central   Jardine   Pencil     36       4.99     179.64
3    2/26/21  Central      Gill      Pen     27      19.99     539.73
4    3/15/21     West   Sorvino   Pencil     56       2.99     167.44
5     4/1/21     East     Jones   Binder     60       4.99     299.40
6    4/18/21  Central   Andrews   Pencil     75       1.99     149.25
7     5/5/21  Central   Jardine   Pencil     90       4.99     449.10
8    5/22/21     West  Thompson   Pencil     32       1.99      63.68
9     6/8/21     East     Jones   Binder     60       8.99     539.40
10   6/25/21  Central    Morgan   Pencil     90       4.99     449.10
11   7/12/21     East    Howard   Binder     29       1.99       7.71
12   7/29/21     East    Parent   Binder     81      19.99   1,619.19
13   8/15/21     East     Jones   Pencil     35       4.99     174.65
14    9/1/21  Central     Smith     Desk      2     125.00     250.00
15   9/18/21     East     Jones  Pen Set     16      15.99     255.84
16   10/5/21  Central    Morgan   Binder     28       8.99     251.72
17  10/22/21     East     Jones      Pen     64       8.99     575.36
18   11/8/21     East    Parent      Pen     15      19.99     299.85
19  11/25/21  Central    Kivell  Pen Set     96       4.99     479.04
20  12/12/21  Central     Smith   Pencil     67       1.29      86.43
21  12/29/21     East    Parent  Pen Set     74      15.99   1,183.26
22   1/15/22  Central      Gill   Binder     46       8.99     413.54
23    2/1/22  Central     Smith   Binder     87      15.00   1,305.00
24   2/18/22     East     Jones   Binder      4       4.99      19.96
25    3/7/22     West   Sorvino   Binder      7      19.99     139.93
26   3/24/22  Central   Jardine  Pen Set     50       4.99     249.50
27   4/10/22  Central   Andrews   Pencil     66       1.99     131.34
28   4/27/22     East    Howard      Pen     96       4.99     479.04
29   5/14/22  Central      Gill   Pencil     53       1.29      68.37
30   5/31/22  Central      Gill   Binder     80       8.99     719.20
31   6/17/22  Central    Kivell     Desk      5     125.00     625.00
32    7/4/22     East     Jones  Pen Set     62       4.99     309.38
33   7/21/22  Central    Morgan  Pen Set     55      12.49     686.95
34    8/7/22  Central    Kivell  Pen Set     42      23.95   1,005.90
35   8/24/22     West   Sorvino     Desk      3     275.00     825.00
36   9/10/22  Central      Gill   Pencil      7       1.29       9.03
37   9/27/22     West   Sorvino      Pen     76       1.99     151.24
38  10/14/22     West  Thompson   Binder     57      19.99   1,139.43
39  10/31/22  Central   Andrews   Pencil     14       1.29      18.06
40  11/17/22  Central   Jardine   Binder     11       4.99      54.89
41   12/4/22  Central   Jardine   Binder     94      19.99   1,879.06
42  12/21/22  Central   Andrews   Binder     28       4.99     139.72

In [16]:
data = pd.read_csv('./SampleData.csv')
X = data.iloc[:,0:4]
Y = data.iloc[:,4:]
# print(X)      // string
# print(Y)      // numerical


# training it

from sklearn.model_selection import train_test_split

Y_train,Y_test = train_test_split(Y,test_size=0.2)
Y_train
Y_test

    Units  Unit Cost       Total
27     66       1.99     131.34
8      32       1.99      63.68
16     28       8.99     251.72
28     96       4.99     479.04
12     81      19.99   1,619.19
10     90       4.99     449.10
26     50       4.99     249.50
5      60       4.99     299.40
40     11       4.99      54.89